version: "3"

vars:
  slug_base: mozumasu
  title: "Default Title"
  type: "tech"
  slug_suffix: "{{ if .s }}{{ .s }}{{ else }}new-article{{ end }}"
  slug: "{{.slug_base}}-{{.slug_suffix}}"

tasks:
  default:
    desc: "Show available tasks and execute the selected one using fzf"
    silent: true
    cmds:
      - |
        selected_task=$(task -l | awk 'NR > 1 && $2 !="default:" { sub(/:$/, "", $2); print $2 }' | \
          fzf --prompt="Select a Task> " \
              --preview="task -l")
        if [ -n "$selected_task" ]; then
          task "$selected_task"
        else
          echo "No task selected."
        fi

  # プレビューを開く
  pv:
    desc: "Preview selected article in the browser"
    silent: true
    cmds:
      - |
        selected_file=$(find slides -type f -name "*.mdx" | fzf --prompt="Select an Slide: ")
        if [ -z "$selected_file" ]; then
          echo "No file selected."
          exit 1
        fi
        file_path=$(echo "$selected_file" | sed 's/\.mdx$//')
        pnpm mdx-deck $file_path
